CXX=gcc

CXXFLAGS_HASWELL=-O2 -march=core-avx2 -fopenmp -DAVX_256 -DN_THREADS=8
CXXFLAGS_KNL=-O2 -march=knl -fopenmp -DAVX_512 -DN_THREADS=256

MAIN=main.c
HASWELL=Haswell.c
KNL=Knl.c

OUTPUT_HASWELL=haswell_256
OUTPUT_KNL=knl_512

all: $(OUTPUT_HASWELL) $(OUTPUT_KNL)

$(OUTPUT_HASWELL): Makefile $(MAIN) $(HASWELL)
	$(CXX) $(MAIN) $(HASWELL) $(CXXFLAGS_HASWELL) -o $(OUTPUT_HASWELL)

$(OUTPUT_KNL): Makefile $(MAIN) $(KNL)
	$(CXX) $(MAIN) $(KNL) $(CXXFLAGS_KNL) -o $(OUTPUT_KNL)

clean:
	@rm $(OUTPUT_HASWELL) $(OUTPUT_KNL)
