#ifndef __UARCH__
#define __UARCH__

#include <stdint.h>

#include "cpufetch.hpp"

typedef uint32_t MICROARCH;

enum {
  UARCH_UNKNOWN,
  // INTEL //
  UARCH_P5,
  UARCH_P6,
  UARCH_DOTHAN,
  UARCH_YONAH,
  UARCH_MEROM,
  UARCH_PENYR,
  UARCH_NEHALEM,
  UARCH_WESTMERE,
  UARCH_BONNELL,
  UARCH_SALTWELL,
  UARCH_SANDY_BRIDGE,
  UARCH_SILVERMONT,
  UARCH_IVY_BRIDGE,
  UARCH_HASWELL,
  UARCH_BROADWELL,
  UARCH_AIRMONT,
  UARCH_KABY_LAKE,
  UARCH_COMET_LAKE,
  UARCH_ROCKET_LAKE,
  UARCH_AMBER_LAKE,
  UARCH_WHISKEY_LAKE,
  UARCH_SKYLAKE,
  UARCH_CASCADE_LAKE,
  UARCH_COOPER_LAKE,
  UARCH_KNIGHTS_LANDING,
  UARCH_KNIGHTS_MILL,
  UARCH_GOLDMONT,
  UARCH_PALM_COVE,
  UARCH_SUNNY_COVE,
  UARCH_GOLDMONT_PLUS,
  UARCH_TREMONT,
  UARCH_LAKEMONT,
  UARCH_COFFEE_LAKE,
  UARCH_ITANIUM,
  UARCH_KNIGHTS_FERRY,
  UARCH_KNIGHTS_CORNER,
  UARCH_WILLAMETTE,
  UARCH_NORTHWOOD,
  UARCH_PRESCOTT,
  UARCH_CEDAR_MILL,
  UARCH_ITANIUM2,
  UARCH_ICE_LAKE,
  UARCH_TIGER_LAKE,
  UARCH_ALDER_LAKE,
  UARCH_RAPTOR_LAKE,
  // AMD //
  UARCH_AM486,
  UARCH_AM5X86,
  UARCH_K6,
  UARCH_K7,
  UARCH_K8,
  UARCH_K10,
  UARCH_PUMA_2008,
  UARCH_BOBCAT,
  UARCH_BULLDOZER,
  UARCH_PILEDRIVER,
  UARCH_STEAMROLLER,
  UARCH_EXCAVATOR,
  UARCH_JAGUAR,
  UARCH_PUMA_2014,
  UARCH_ZEN,
  UARCH_ZEN_PLUS,
  UARCH_ZEN2,
  UARCH_ZEN3,
  UARCH_ZEN3_PLUS,
  UARCH_ZEN4
};

struct uarch {
  MICROARCH uarch;
  char* uarch_str;
};

struct uarch* get_uarch(struct cpu* cpu);
const char* get_str_uarch(struct cpu* cpu);
void free_uarch_struct(struct uarch* arch);

#endif
